-- MySQL Script generated by MySQL Workbench
-- 05/24/17 18:54:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pzmj
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pzmj` ;

-- -----------------------------------------------------
-- Schema pzmj
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pzmj` DEFAULT CHARACTER SET utf8 ;
USE `pzmj` ;

-- -----------------------------------------------------
-- Table `pzmj`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pzmj`.`accounts` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `channel_id` INT(11) NULL DEFAULT NULL COMMENT '渠道id',
  `account` VARCHAR(255) NULL DEFAULT NULL COMMENT '账户名',
  `pass_word` VARCHAR(255) NULL DEFAULT NULL COMMENT '密码',
  PRIMARY KEY (`id`),
  INDEX `idx_accounts_deleted_at` (`deleted_at` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pzmj`.`admin_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pzmj`.`admin_access` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_id` SMALLINT(6) UNSIGNED NOT NULL,
  `node_id` SMALLINT(6) UNSIGNED NOT NULL,
  `remark` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `U_admin_access_role_id_node_id` (`role_id` ASC, `node_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pzmj`.`admin_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pzmj`.`admin_role` (
  `id` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `sysIds` VARCHAR(255) NULL DEFAULT '',
  `remark` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `N_admin_role_name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pzmj`.`admin_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pzmj`.`admin_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `uname` VARCHAR(32) NOT NULL COMMENT '用户账号',
  `upass` CHAR(32) NOT NULL COMMENT '用户密码',
  `usalt` CHAR(6) NOT NULL COMMENT '随机因子',
  `ltime` TIMESTAMP NULL DEFAULT NULL COMMENT '登录时间',
  `lip` VARCHAR(32) NULL DEFAULT NULL COMMENT '登录IP',
  `role_id` INT(11) NOT NULL COMMENT '角色ID',
  `status` TINYINT(4) NULL DEFAULT '1' COMMENT '登录状态 1=允许 0=禁止',
  `created_at` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `updated_at` TIMESTAMP NULL DEFAULT NULL COMMENT '更新时间',
  `expire` SMALLINT(6) NOT NULL COMMENT '有效期(天) -1=永久',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `U_admin_user_uname` (`uname` ASC),
  INDEX `N_admin_user_role_id` (`role_id` ASC),
  INDEX `N_admin_user_created_at` (`created_at` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pzmj`.`battle_records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pzmj`.`battle_records` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `room_id` INT(11) NULL DEFAULT NULL COMMENT '房间id',
  `round` INT(11) NULL DEFAULT NULL COMMENT '局数',
  `result` VARCHAR(255) NULL DEFAULT NULL COMMENT '结果 map[int]int',
  `play_back` LONGTEXT NULL DEFAULT NULL COMMENT '回放记录',
  PRIMARY KEY (`id`),
  INDEX `idx_battle_records_deleted_at` (`deleted_at` ASC),
  INDEX `idx_battle_records_room_id` (`room_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pzmj`.`log_diamonds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pzmj`.`log_diamonds` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL COMMENT '用户id',
  `diamond` INT(11) NULL DEFAULT NULL COMMENT '钻石(正数增加，负数消费)',
  `type` INT(11) NULL DEFAULT NULL COMMENT '钻石消费类型',
  PRIMARY KEY (`id`),
  INDEX `idx_log_diamonds_deleted_at` (`deleted_at` ASC),
  INDEX `idx_log_diamonds_user_id` (`user_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pzmj`.`log_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pzmj`.`log_items` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL COMMENT '用户id',
  `item_id` INT(11) NULL DEFAULT NULL COMMENT '物品id',
  `count` INT(11) NULL DEFAULT NULL COMMENT '数量',
  `type` INT(11) NULL DEFAULT NULL COMMENT '通过何种方式获取',
  PRIMARY KEY (`id`),
  INDEX `idx_log_items_deleted_at` (`deleted_at` ASC),
  INDEX `idx_log_items_user_id` (`user_id` ASC),
  INDEX `idx_log_items_item_id` (`item_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pzmj`.`log_logins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pzmj`.`log_logins` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `area_id` INT(11) NULL DEFAULT NULL COMMENT '区域id',
  `user_id` VARCHAR(255) NULL DEFAULT NULL COMMENT '用户id',
  `ip` VARCHAR(255) NULL DEFAULT NULL COMMENT 'ip地址',
  PRIMARY KEY (`id`),
  INDEX `idx_log_logins_user_id` (`user_id` ASC),
  INDEX `idx_log_logins_deleted_at` (`deleted_at` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pzmj`.`mails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pzmj`.`mails` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `from_id` INT(11) NULL DEFAULT NULL COMMENT '邮件发送人用户id',
  `to_id` INT(11) NULL DEFAULT NULL COMMENT '接收人用户id',
  `title` VARCHAR(255) NULL DEFAULT NULL COMMENT '标题',
  `goods` VARCHAR(255) NULL DEFAULT NULL COMMENT '邮件里包含的物品',
  `context` VARCHAR(255) NULL DEFAULT NULL COMMENT '内容',
  `watched` INT(11) NULL DEFAULT NULL COMMENT '是否已查看',
  `used` INT(11) NULL DEFAULT NULL COMMENT '是否已领取',
  `type` INT(11) NULL DEFAULT NULL COMMENT '1:系统邮件 2：非系统邮件',
  PRIMARY KEY (`id`),
  INDEX `idx_mails_deleted_at` (`deleted_at` ASC),
  INDEX `idx_mails_from_id` (`from_id` ASC),
  INDEX `idx_mails_to_id` (`to_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pzmj`.`notices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pzmj`.`notices` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL COMMENT '标题',
  `content` VARCHAR(255) NULL DEFAULT NULL COMMENT '内容',
  `status` INT(11) NULL DEFAULT NULL COMMENT '0:无效 1:有效',
  `start_time` TIMESTAMP NULL DEFAULT NULL COMMENT '开始时间',
  `end_time` TIMESTAMP NULL DEFAULT NULL COMMENT '结束时间',
  `area_ids` VARCHAR(255) NULL DEFAULT NULL COMMENT '区域id',
  `type` INT(11) NULL DEFAULT NULL COMMENT '类型 1-公告 2-跑马灯',
  `show_position` INT(11) NULL DEFAULT NULL COMMENT '显示位置 1-大厅',
  `channel_id` INT(11) NULL DEFAULT NULL COMMENT '显示的渠道ID 0-全渠道',
  `is_top` INT(11) NULL DEFAULT NULL COMMENT '是否置顶 1-是 0-否',
  PRIMARY KEY (`id`),
  INDEX `idx_notices_channel_id` (`channel_id` ASC),
  INDEX `idx_notices_deleted_at` (`deleted_at` ASC),
  INDEX `idx_notices_type` (`type` ASC),
  INDEX `idx_notices_start_time_and_end_time` (`start_time`,`end_time`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pzmj`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pzmj`.`orders` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL COMMENT '用户id',
  `channel_id` INT(11) NULL DEFAULT NULL COMMENT '渠道id',
  `account_id` INT(11) NULL DEFAULT NULL COMMENT '账户id',
  `order_no` VARCHAR(255) NULL DEFAULT NULL COMMENT '订单号',
  `cargo_id` INT(11) NULL DEFAULT NULL COMMENT '商品id',
  `rmb` INT(11) NULL DEFAULT NULL COMMENT '充值金额,单位元',
  `diamond` INT(11) NULL DEFAULT NULL COMMENT '获取钻石数',
  `status` INT(11) NULL DEFAULT NULL COMMENT '状态 0:未处理 1：已处理',
  `pay_type` INT(4) NULL DEFAULT NULL COMMENT '支付方式 1-支付宝 2-微信 3-银联',
  PRIMARY KEY (`id`),
  INDEX `idx_orders_status` (`status` ASC),
  INDEX `idx_orders_created_at` (`created_at` ASC),
  INDEX `idx_orders_deleted_at` (`deleted_at` ASC),
  INDEX `idx_orders_user_id` (`user_id` ASC),
  INDEX `idx_orders_channel_id` (`channel_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pzmj`.`room_records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pzmj`.`room_records` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `room_id` INT(11) NULL DEFAULT NULL COMMENT '房间号',
  `room_type` INT(11) NULL DEFAULT NULL COMMENT '房间类型',
  `battle_record_id` INT(11) NULL DEFAULT NULL COMMENT '战绩id',
  `user_id` INT(11) NULL DEFAULT NULL COMMENT '用户id',
  `position` INT(11) NULL DEFAULT NULL COMMENT '位置',
  `win` INT(11) NULL DEFAULT NULL COMMENT '0:输 1:赢',
  PRIMARY KEY (`id`),
  INDEX `idx_room_records_room_id` (`room_id` ASC),
  INDEX `idx_room_records_battle_record_id` (`battle_record_id` ASC),
  INDEX `idx_room_records_user_id` (`user_id` ASC),
  INDEX `idx_room_records_deleted_at` (`deleted_at` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pzmj`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pzmj`.`rooms` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL COMMENT '用户id',
  `type` INT(11) NULL DEFAULT NULL COMMENT '房间类型',
  `rules` VARCHAR(255) NULL DEFAULT NULL COMMENT '房间规则',
  `UniqueCode` varchar(255) DEFAULT NULL COMMENT 'room唯一标识';
  PRIMARY KEY (`id`),
  INDEX `idx_rooms_deleted_at` (`deleted_at` ASC),
  INDEX `idx_rooms_user_id` (`user_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pzmj`.`suggestions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pzmj`.`suggestions` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL COMMENT '用户id',
  `title` VARCHAR(255) NULL DEFAULT NULL COMMENT '标题',
  `content` VARCHAR(255) NULL DEFAULT NULL COMMENT '内容',
  PRIMARY KEY (`id`),
  INDEX `idx_suggestions_deleted_at` (`deleted_at` ASC),
  INDEX `idx_suggestions_user_id` (`user_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pzmj`.`user_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pzmj`.`user_items` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL COMMENT '用户id',
  `item_id` INT(11) NULL DEFAULT NULL COMMENT '物品id',
  `count` INT(11) NULL DEFAULT NULL COMMENT '物品数量',
  PRIMARY KEY (`id`),
  INDEX `idx_user_items_deleted_at` (`deleted_at` ASC),
  INDEX `idx_user_items_user_id` (`user_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `pzmj`.`user_deny`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pzmj`.`user_deny`(
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `user_id` INT COMMENT '用户ID',
  `deny_type` TINYINT COMMENT '禁止类型 1-登录 2-发言',
  `start_time` TIMESTAMP NULL DEFAULT NULL COMMENT '开始时间',
  `end_time` TIMESTAMP NULL DEFAULT NULL COMMENT '结束时间',
  `status` TINYINT COMMENT '是否启用 1-启用 0-未启用',
  `deny_time` TIMESTAMP NULL DEFAULT NULL COMMENT '禁止操作时间 后台用',
  `deny_admin_id` INT COMMENT '禁止操作员 后台用',
  `allow_time` TIMESTAMP NULL DEFAULT NULL COMMENT '解禁操作时间 后台用',
  `allow_admin_id` INT COMMENT '解禁操作员 后台用',
  PRIMARY KEY (`id`),
  INDEX `idx_user_deny_user_id` (`user_id`),
  INDEX `idx_user_deny_start_time_and_end_time` (`start_time`, `end_time`),
  INDEX `idx_user_deny_deleted_at` (`deleted_at`))
ENGINE=INNODB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `pzmj`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pzmj`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `account_id` INT(11) NULL DEFAULT NULL COMMENT '账户id',
  `union_id` VARCHAR(255) NULL DEFAULT NULL COMMENT '微信统一id',
  `nick_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '昵称',
  `sex` INT(11) NULL DEFAULT NULL COMMENT '性别 1:男 2:女',
  `province` VARCHAR(255) NULL DEFAULT NULL COMMENT '省份',
  `city` VARCHAR(255) NULL DEFAULT NULL COMMENT '城市',
  `country` VARCHAR(255) NULL DEFAULT NULL COMMENT '国家',
  `sid` VARCHAR(255) NULL DEFAULT NULL COMMENT 'sid,用户唯一标识',
  `channel_id` INT(11) NULL DEFAULT NULL COMMENT '渠道id',
  `type` INT(11) NULL DEFAULT NULL,
  `state` INT(11) NULL DEFAULT NULL,
  `coin` INT(11) NULL DEFAULT NULL,
  `card` INT(11) NULL DEFAULT NULL,
  `diamond` INT(11) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `win_week` INT(11) NULL DEFAULT NULL,
  `week_count` INT(11) NULL DEFAULT NULL,
  `usual_area` INT(11) NULL DEFAULT NULL,
  `benefit_time` VARCHAR(255) NULL DEFAULT NULL,
  `benefit_count` INT(11) NULL DEFAULT NULL,
  `last_ip` VARCHAR(255) NULL DEFAULT NULL,
  `gps_lng` DOUBLE NULL DEFAULT NULL,
  `gps_lat` DOUBLE NULL DEFAULT NULL,
  `is_robot` INT(11) NULL DEFAULT NULL,
  `room_id` INT(11) NULL DEFAULT NULL,
  `icon` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `union_id` (`union_id` ASC),
  INDEX `idx_users_deleted_at` (`deleted_at` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
